.TH ocamlweb 1 "June 15, 2001"

.SH NAME
ocamlweb \- A literate programming tool for Objective Caml


.SH SYNOPSIS
.B ocamlweb
[
.B options
]
.B files


.SH DESCRIPTION

.B ocamlweb
is a literate programming tool for Objective Caml.
It creates a LaTeX document with both documentation and code
(implementations and interfaces) from a set of Caml files.
Documentation is inserted into ocaml files as comments.
Conversely, code may be quoted inside documentation between square brackets.
See the ocamlweb web site for documentation and examples.


.SH OPTIONS

.TP
.B \-h
Help. Will give you the complete list of options accepted by ocamlweb.


.SH AUTHORS
.I Jean-Christophe Filliatre <filliatr@lri.fr>
.br
.I Claude Marche <marche@lri.fr>


.SH SEE ALSO

.I
Ocamlweb web site: http://www.lri.fr/~filliatr/ocamlweb/
.br
.I
The Objective Caml web site: http://caml.inria.fr/
